spring.application.name=knowledge-platform
server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/knowledge_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Admin@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

# Tomcat 大文件上传支持
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.connection-timeout=600000
spring.servlet.multipart.file-size-threshold=50MB

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai

preview.onlyoffice.enabled=false
preview.onlyoffice.server-url=http://localhost:8088
preview.onlyoffice.public-base-url=http://192.168.1.142
preview.office.command=C:/Program Files/LibreOffice/program/soffice.exe

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://192.168.1.142,http://192.168.1.142:80}


# Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
